# Welcome to Jekyll!

url: "https://pulsy-bh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/veranda77.fr"
# baseurl: ""

# Build settings
plugins:
  - jekyll-sitemap #https://github.com/jekyll/jekyll-sitemap
  - jekyll-minifier #https://github.com/digitalsparky/jekyll-minifier
  - html-proofer #https://github.com/gjtorikian/html-proofer

# Where things are
source              : ./src
destination         : ./_site


# layouts_dir         : _layouts # Don't rename this, watch wouldn't't work
# data_dir            : _data # Don't rename this, watch wouldn't't work
# includes_dir        : _includes # Don't rename this, watch wouldn't't work

layouts_dir         : ./src/_layouts # Don't rename this, watch wouldn't't work
data_dir            : ./src/_data # Don't rename this, watch wouldn't't work
includes_dir        : ./src/_includes # Don't rename this, watch wouldn't't work


theme: null
remote_theme: null
